import BlogPost from "./BlogPost/BlogPost.component.jsx"
import AdminDashboard from "./AdminDashboard/AdminDashboard.component.jsx"
import AdminMenu from "./AdminMenu/AdminMenu.component.jsx"
import AdminRoute from "./AdminRoute/AdminRoute.component.jsx"
import ChangePassword from "./ChangePassword/ChangePassword.component.jsx"
import Checkbox from "./Checkbox/Checkbox.component.jsx"
import ContactForm from "./ContactForm/ContactForm.component.jsx"
import DeleteImage from "./DeleteImage/DeleteImage.component.jsx"
import Footer from "./Footer/Footer.component.jsx"
import ForgotPassword from "./ForgotPassword/ForgotPassword.component.jsx"
import ImageBox from "./ImageBox/ImageBox.component.jsx"
import Layout from "./Layout/Layout.component.jsx"
import NavDesk from "./NavDesk/NavDesk.component.jsx"
import NavList from "./NavList/NavList.component.jsx"
import NavMobile from "./NavMobile/NavMobile.component.jsx"
import ResetPassword from "./ResetPassword/ResetPassword.component.jsx"
import ToggleNavButton from "./ToggleNavButton/ToggleNavButton.component.jsx"
import UploadImage from "./UploadImage/UploadImage.component.jsx"
import BlogPageContent from "./BlogPageContent/BlogPageContent.component.jsx"
import ContactPageContent from "./ContactPageContent/ContactPageContent.component.jsx"
import HomePageContent from "./HomePageContent/HomePageContent.component.jsx"
import LoginPageContent from "./LoginPageContent/LoginPageContent.component.jsx"
import PortfolioPageContent from "./PortfolioPageContent/PortfolioPageContent.component.jsx"
import ResumePageContent from "./ResumePageContent/ResumePageContent.component.jsx"
import SkillsPageContent from "./SkillsPageContent/SkillsPageContent.component.jsx"
import TComp from "./typography/typography.components.js"
export const CIndex = {
		BlogPost,AdminDashboard,AdminMenu,AdminRoute,ChangePassword,Checkbox,ContactForm,DeleteImage,Footer,ForgotPassword,ImageBox,Layout,NavDesk,NavList,NavMobile,ResetPassword,ToggleNavButton,UploadImage,BlogPageContent,ContactPageContent,HomePageContent,LoginPageContent,PortfolioPageContent,ResumePageContent,SkillsPageContent, TComp
	}
	export default CIndex
	